import os

CEIS_SHOP_HOSTNAME=os.getenv("CEIS_SHOP_HOSTNAME", "localhost")
CEIS_SHOP_PORT=os.getenv("CEIS_SHOP_PORT", "8050")
CEIS_MONITOR_HOSTNAME=os.getenv("CEIS_MONITOR_HOSTNAME", "localhost")
CEIS_MONITOR_PORT=os.getenv("CEIS_MONITOR_PORT", "8051")
